version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "uFinance"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16beli24ubqds"
s3_prefix = "uFinance"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBUsername=\"admin\" DBPassword=\"adminpass\""
